//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpreadsheetView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpreadsheetView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Spreadsheet.
        /// </summary>
        internal static string DefaultSpreadsheetName {
            get {
                return ResourceManager.GetString("DefaultSpreadsheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Formula: The formula cannot have circular references..
        /// </summary>
        internal static string ErrorDialogTextCircularReference {
            get {
                return ResourceManager.GetString("ErrorDialogTextCircularReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open new spreadsheet..
        /// </summary>
        internal static string ErrorDialogTextCouldNotOpenNew {
            get {
                return ResourceManager.GetString("ErrorDialogTextCouldNotOpenNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred populating the cells.  Invalid cell coordinates in file..
        /// </summary>
        internal static string ErrorDialogTextFileLoad {
            get {
                return ResourceManager.GetString("ErrorDialogTextFileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Formula: The formula is not correctly formatted..
        /// </summary>
        internal static string ErrorDialogTextFormulaFormat {
            get {
                return ResourceManager.GetString("ErrorDialogTextFormulaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recent changes have been made or saved..
        /// </summary>
        internal static string ErrorDialogTextNoChangesMade {
            get {
                return ResourceManager.GetString("ErrorDialogTextNoChangesMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred opening the file..
        /// </summary>
        internal static string ErrorDialogTextOpeningFile {
            get {
                return ResourceManager.GetString("ErrorDialogTextOpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred opening the file..
        /// </summary>
        internal static string ErrorDialogTextOpeningFileUnknown {
            get {
                return ResourceManager.GetString("ErrorDialogTextOpeningFileUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred recalculating the cells.  Please verify that all formulas are valid and reference valid cell names..
        /// </summary>
        internal static string ErrorDialogTextRecalculatingCells {
            get {
                return ResourceManager.GetString("ErrorDialogTextRecalculatingCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred saving the file..
        /// </summary>
        internal static string ErrorDialogTextSavingFile {
            get {
                return ResourceManager.GetString("ErrorDialogTextSavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred saving the file..
        /// </summary>
        internal static string ErrorDialogTextSavingFileUnknown {
            get {
                return ResourceManager.GetString("ErrorDialogTextSavingFileUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred undoing the previous operation..
        /// </summary>
        internal static string ErrorDialogTextUndoUnknown {
            get {
                return ResourceManager.GetString("ErrorDialogTextUndoUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred..
        /// </summary>
        internal static string ErrorDialogTextUnknown {
            get {
                return ResourceManager.GetString("ErrorDialogTextUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spreadsheet Error.
        /// </summary>
        internal static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS3505 Cloud Spreadsheet.
        /// </summary>
        internal static string HelpDialogTextAbout1 {
            get {
                return ResourceManager.GetString("HelpDialogTextAbout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Forms Spreadsheet Application v. 1.0.
        /// </summary>
        internal static string HelpDialogTextAbout2 {
            get {
                return ResourceManager.GetString("HelpDialogTextAbout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS 3505 Spring 2013.
        /// </summary>
        internal static string HelpDialogTextAbout3 {
            get {
                return ResourceManager.GetString("HelpDialogTextAbout3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University of Utah.
        /// </summary>
        internal static string HelpDialogTextAbout4 {
            get {
                return ResourceManager.GetString("HelpDialogTextAbout4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by John Chase, Thomas Gonsor, Michael Quigley, Zach Wilcox.
        /// </summary>
        internal static string HelpDialogTextAbout5 {
            get {
                return ResourceManager.GetString("HelpDialogTextAbout5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the Spreadsheet.
        /// </summary>
        internal static string HelpDialogTextContents1 {
            get {
                return ResourceManager.GetString("HelpDialogTextContents1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can set the contents of a cell by typing text into the Contents box. The cells accept numbers, plain text or formulas as their contents.  Formulas need to have the equals sign (=) in front of them and need to use standard infix notation in order for the spreadsheet to accurately calculate the end value (e.g. =A2/A3 + A4*(A5 - 1)). Additionally any cells referenced in the formula need to have a numeric value associated with them..
        /// </summary>
        internal static string HelpDialogTextContents2 {
            get {
                return ResourceManager.GetString("HelpDialogTextContents2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can select different cells by using the mouse, the arrow keys or by pressing Enter. If you want to save, open or create a new spreadsheet, simply use the file menu. You can have multiple spreadsheets open at a time. Enjoy!.
        /// </summary>
        internal static string HelpDialogTextContents3 {
            get {
                return ResourceManager.GetString("HelpDialogTextContents3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpDialogTitle {
            get {
                return ResourceManager.GetString("HelpDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string InputBoxLabelNameText {
            get {
                return ResourceManager.GetString("InputBoxLabelNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string InputBoxLabelPasswordText {
            get {
                return ResourceManager.GetString("InputBoxLabelPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of the spreadsheet you would like to edit..
        /// </summary>
        internal static string InputBoxTextEdit {
            get {
                return ResourceManager.GetString("InputBoxTextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of the spreadsheet you would like to create..
        /// </summary>
        internal static string InputBoxTextNew {
            get {
                return ResourceManager.GetString("InputBoxTextNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Spreadsheet File.
        /// </summary>
        internal static string OpenDialogTitle {
            get {
                return ResourceManager.GetString("OpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spreadsheet Files (*.ss)|*.ss|All Files (*.*)|*.*.
        /// </summary>
        internal static string SaveAsDialogFileFilterTypes {
            get {
                return ResourceManager.GetString("SaveAsDialogFileFilterTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a Spreadsheet File.
        /// </summary>
        internal static string SaveAsDialogTitle {
            get {
                return ResourceManager.GetString("SaveAsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes you made to &quot;%&quot; ?.
        /// </summary>
        internal static string SaveChangesDialogText {
            get {
                return ResourceManager.GetString("SaveChangesDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes?.
        /// </summary>
        internal static string SaveChangesDialogTitle {
            get {
                return ResourceManager.GetString("SaveChangesDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ss.
        /// </summary>
        internal static string SpreadsheetFileExtension {
            get {
                return ResourceManager.GetString("SpreadsheetFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon SpreadsheetIcon {
            get {
                object obj = ResourceManager.GetObject("SpreadsheetIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
